services:
- postgresql
before_script:
- psql -c 'create database controledeprocesso;' -U postgres
- psql -U postgres -d controledeprocesso -f script/create_tables.sql
- psql -U postgres -d controledeprocesso -f script/fill_tables.sql
 - cd src/ControleDeProcesso
# - ls
language: java
jdk:
  - oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
